name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.16', '1.17' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
    
      - name: Build
        run: go build ./...
        
      - name: Test
        run: go test -v -coverprofile=coverage.txt ./...
        
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.txt
