name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
    
      - name: Build
        run: go build ./...
        
      - name: Test
        run: go test -v -coverprofile=./coverage.out ./...
        
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./coverage.out
        
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.out
